In [28]:
# load the dataset
import pandas as pd
df = pd.read_csv("train.csv")

In [29]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [30]:
df.Parch.max()

np.int64(6)

In [31]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [32]:
# Drop irrelevent columns
df = df.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)

#check the results
df.head(10)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S
5         0       3    male   NaN      0      0   8.4583        Q
6         0       1    male  54.0      0      0  51.8625        S
7         0       3    male   2.0      3      1  21.0750        S
8         1       3  female  27.0      0      2  11.1333        S
9         1       2  female  14.0      1      0  30.0708        C

In [33]:
# one-hot encode the "Pclass" column
df = pd.get_dummies(df, columns=['Pclass'], drop_first=True)

df.head(10)

   Survived     Sex   Age  SibSp  Parch     Fare Embarked  Pclass_2  Pclass_3
0         0    male  22.0      1      0   7.2500        S     False      True
1         1  female  38.0      1      0  71.2833        C     False     False
2         1  female  26.0      0      0   7.9250        S     False      True
3         1  female  35.0      1      0  53.1000        S     False     False
4         0    male  35.0      0      0   8.0500        S     False      True
5         0    male   NaN      0      0   8.4583        Q     False      True
6         0    male  54.0      0      0  51.8625        S     False     False
7         0    male   2.0      3      1  21.0750        S     False      True
8         1  female  27.0      0      2  11.1333        S     False      True
9         1  female  14.0      1      0  30.0708        C      True     False

In [34]:
# One-hot encode the 'Emberked' column
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,male,22.0,1,0,7.2500,False,True,False,True
1,1,female,38.0,1,0,71.2833,False,False,False,False
2,1,female,26.0,0,0,7.9250,False,True,False,True
3,1,female,35.0,1,0,53.1000,False,False,False,True
4,0,male,35.0,0,0,8.0500,False,True,False,True
5,0,male,NaN,0,0,8.4583,False,True,True,False
6,0,male,54.0,0,0,51.8625,False,False,False,True
7,0,male,2.0,3,1,21.0750,False,True,False,True
8,1,female,27.0,0,2,11.1333,False,True,False,True
9,1,female,14.0,1,0,30.0708,True,False,False,False

In [35]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

In [36]:
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False
2,1,1,26.0,0,0,7.9250,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,True
4,0,0,35.0,0,0,8.0500,False,True,False,True
5,0,0,NaN,0,0,8.4583,False,True,True,False
6,0,0,54.0,0,0,51.8625,False,False,False,True
7,0,0,2.0,3,1,21.0750,False,True,False,True
8,1,1,27.0,0,2,11.1333,False,True,False,True
9,1,1,14.0,1,0,30.0708,True,False,False,False

In [37]:
df.isna().sum()

Survived        0
Sex             0
Age           177
SibSp           0
Parch           0
Fare            0
Pclass_2        0
Pclass_3        0
Embarked_Q      0
Embarked_S      0
dtype: int64

Applying inputation

In [38]:
# Calculate median age
median_age = df['Age'].median()
print(median_age)

28.0

In [39]:
df.fillna({'Age':median_age},inplace=True)
df.isna().sum()

Survived      0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Pclass_2      0
Pclass_3      0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [40]:
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False
2,1,1,26.0,0,0,7.9250,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,True
4,0,0,35.0,0,0,8.0500,False,True,False,True
5,0,0,28.0,0,0,8.4583,False,True,True,False
6,0,0,54.0,0,0,51.8625,False,False,False,True
7,0,0,2.0,3,1,21.0750,False,True,False,True
8,1,1,27.0,0,2,11.1333,False,True,False,True
9,1,1,14.0,1,0,30.0708,True,False,False,False

In [41]:
# Convert boolean columns to integers (True -> 1, False -> 0)
boolean_cols = ['Pclass_2', 'Pclass_3', 'Embarked_Q', 'Embarked_S']
for col in boolean_cols:
    df[col] = df[col].astype(int)

# Re-check the head to confirm the conversion
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,0,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0,0
2,1,1,26.0,0,0,7.9250,0,1,0,1
3,1,1,35.0,1,0,53.1000,0,0,0,1
4,0,0,35.0,0,0,8.0500,0,1,0,1
5,0,0,28.0,0,0,8.4583,0,1,1,0
6,0,0,54.0,0,0,51.8625,0,0,0,1
7,0,0,2.0,3,1,21.0750,0,1,0,1
8,1,1,27.0,0,2,11.1333,0,1,0,1
9,1,1,14.0,1,0,30.0708,1,0,0,0

Normalize the Age Value

In [42]:
# Find the maximum age in the dataset
max_age = df["Age"].max()
print(max_age)

df["Age_Normalized"] = df["Age"] / max_age
df.head()

80.0

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized
0,0,0,22.0,1,0,7.2500,0,1,0,1,0.2750
1,1,1,38.0,1,0,71.2833,0,0,0,0,0.4750
2,1,1,26.0,0,0,7.9250,0,1,0,1,0.3250
3,1,1,35.0,1,0,53.1000,0,0,0,1,0.4375
4,0,0,35.0,0,0,8.0500,0,1,0,1,0.4375

In [43]:
# Check for zeros in the 'Fare' column
zero_count = (df['Fare'] == 0).sum()

if zero_count > 0:
    print(f"✅ Yes, the 'Fare' column contains {zero_count} zero(s).")
else:
    print("✅ No zeros found in the 'Fare' column.")

✅ Yes, the 'Fare' column contains 15 zero(s).

In [44]:
#remove Fare 0
df_cleaned = df[df['Fare'] != 0].copy()
df = df_cleaned

Scale the fare

In [45]:
import numpy as np
df['Log_Fare'] = np.log10(df['Fare'])
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized,Log_Fare
0,0,0,22.0,1,0,7.2500,0,1,0,1,0.2750,0.860338
1,1,1,38.0,1,0,71.2833,0,0,0,0,0.4750,1.852988
2,1,1,26.0,0,0,7.9250,0,1,0,1,0.3250,0.898999
3,1,1,35.0,1,0,53.1000,0,0,0,1,0.4375,1.725095
4,0,0,35.0,0,0,8.0500,0,1,0,1,0.4375,0.905796
5,0,0,28.0,0,0,8.4583,0,1,1,0,0.3500,0.927283
6,0,0,54.0,0,0,51.8625,0,0,0,1,0.6750,1.714853
7,0,0,2.0,3,1,21.0750,0,1,0,1,0.0250,1.323768
8,1,1,27.0,0,2,11.1333,0,1,0,1,0.3375,1.046624
9,1,1,14.0,1,0,30.0708,1,0,0,0,0.1750,1.478145

In [46]:
# Separate feature(X) and target (y)
X = df.drop(['Survived','Age','Fare'], axis=1,)
y = df['Survived']

In [47]:
X.head()

,Sex,SibSp,Parch,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized,Log_Fare
0,0,1,0,0,1,0,1,0.2750,0.860338
1,1,1,0,0,0,0,0,0.4750,1.852988
2,1,0,0,0,1,0,1,0.3250,0.898999
3,1,1,0,0,0,0,1,0.4375,1.725095
4,0,0,0,0,1,0,1,0.4375,0.905796

In [48]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [49]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [50]:
print(X)

     Sex  SibSp  Parch  Pclass_2  Pclass_3  Embarked_Q  Embarked_S  \
0      0      1      0         0         1           0           1
1      1      1      0         0         0           0           0
2      1      0      0         0         1           0           1
3      1      1      0         0         0           0           1
4      0      0      0         0         1           0           1
..   ...    ...    ...       ...       ...         ...         ...
886    0      0      0         1         0           0           1
887    1      0      0         0         0           0           1
888    1      1      2         0         1           0           1
889    0      0      0         0         0           0           0
890    0      0      0         0         1           1           0

     Age_Normalized  Log_Fare
0            0.2750  0.860338
1            0.4750  1.852988
2            0.3250  0.898999
3            0.4375  1.725095
4            0.4375  0.905796
..              ...       ...
886          0.3375  1.113943
887          0.2375  1.477121
888          0.3500  1.370143
889          0.3250  1.477121
890          0.4000  0.889302

[876 rows x 9 columns]

In [51]:
# Convert to PyTorch Tensors
X_tensor = torch.tensor(X.to_numpy(dtype="float32"))
y_tensor = torch.tensor(y.to_numpy(dtype="float32")).view(-1, 1)

In [52]:
X = X_tensor
print("X =", X)
y = y_tensor
print("y =", y)

N, D = X.shape
print("N =", N)
print("D =", D)
H1, H2 = 16, 8   # two sets of neurons (hidden layers)
print("H1 =", H1)
print("H2 =", H2)

# 1) Parameters
W1 = (torch.randn(D, H1) * 0.01).requires_grad_()
print("W1 =", W1)
b1 = torch.zeros(H1, requires_grad=True)
print("b1 =", b1)

W2 = (torch.randn(H1, H2) * 0.01).requires_grad_()
print("W2 =", W2)
b2 = torch.zeros(H2, requires_grad=True)
print("b2 =", b2)

W3 = (torch.randn(H2, 1) * 0.01).requires_grad_()
print("W3 =", W3)
b3 = torch.zeros(1, requires_grad=True)
print("b3 =", b3)

X = tensor([[0.0000, 1.0000, 0.0000,  ..., 1.0000, 0.2750, 0.8603],
        [1.0000, 1.0000, 0.0000,  ..., 0.0000, 0.4750, 1.8530],
        [1.0000, 0.0000, 0.0000,  ..., 1.0000, 0.3250, 0.8990],
        ...,
        [1.0000, 1.0000, 2.0000,  ..., 1.0000, 0.3500, 1.3701],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.3250, 1.4771],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.4000, 0.8893]])
y = tensor([[0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.]])
N = 876
D = 9
H1 = 16
H2 = 8
W1 = tensor([[-8.3777e-03,  5.6019e-03,  1.2181e-02,  6.8066e-03, -1.8185e-04,
          6.6687e-03,  6.0881e-03,  7.4099e-03,  7.7890e-03, -2.4615e-02,
          1.6931e-02, -1.0811e-02, -2.0011e-02, -1.7094e-02, -2.0508e-03,
          1.4864e-02],
        [-2.6159e-02,  6.1918e-03,  1.2142e-02, -7.5426e-03,  5.6297e-03,
         -6.9260e-03, -7.7293e-03, -1.4999e-02,  1.3711e-03, -3.1964e-03,
         -1.8867e-02,  2.0619e-02, -6.1733e-03,  6.2916e-04, -7.4364e-03,
          6.7335e-03],
        [-6.7576e-03,  1.0092e-02, -8.3252e-03,  6.5669e-03,  4.9457e-03,
          1.0715e-03,  1.9843e-02, -5.5764e-03,  8.2940e-04, -1.5592e-02,
         -3.0489e-03, -4.2512e-03,  6.2229e-03, -2.1001e-02,  4.5499e-03,
          8.6668e-03],
        [-3.9689e-03,  2.0605e-02,  1.5012e-02, -7.2040e-03, -1.2686e-03,
          4.2694e-03,  5.5952e-03, -4.6188e-04, -4.6347e-04,  1.8906e-02,
          1.8915e-02,  1.9562e-02,  1.0512e-04, -2.3188e-03,  9.1613e-04,
         -6.6752e-04],
        [ 5.9629e-03, -1.5744e-02,  2.4334e-02, -1.7718e-03, -2.0616e-03,
         -4.2150e-03,  9.6540e-03,  1.8822e-04, -7.3759e-03,  1.4777e-02,
         -5.0543e-04, -7.2220e-03, -4.2842e-03, -2.4860e-05, -8.6655e-03,
         -5.4969e-03],
        [ 1.0053e-02, -3.4031e-03,  3.6818e-03,  5.1139e-03, -4.0107e-03,
         -1.3141e-02,  1.1671e-02, -7.4315e-03,  4.0776e-03, -6.8016e-03,
          2.1571e-02, -5.0334e-03, -8.1835e-03,  1.8995e-03, -1.1548e-02,
          1.3512e-02],
        [ 4.1338e-03, -1.3065e-02,  4.1387e-03, -1.3380e-02,  1.5718e-03,
         -1.1552e-03,  5.6123e-03, -1.4535e-02, -9.8252e-03,  1.5912e-03,
         -9.8027e-03,  4.5166e-03,  4.5763e-03, -9.1686e-03,  1.6292e-03,
          1.6139e-02],
        [-1.5897e-02, -7.6889e-03,  9.0411e-03, -6.8448e-03, -4.5561e-03,
          7.1628e-03, -2.6160e-03, -1.0040e-03,  1.0400e-02, -7.0122e-04,
         -1.0268e-02,  7.1152e-03, -2.0301e-03,  3.7993e-03, -4.3287e-03,
          1.6173e-02],
        [-4.1913e-03, -2.1616e-02, -4.4721e-03,  2.4699e-02,  1.1503e-02,
          1.0033e-02,  9.3091e-03,  9.9072e-03,  5.6754e-03, -3.4862e-03,
         -5.7219e-03, -5.2451e-03,  2.7269e-03, -1.3885e-02, -1.1364e-03,
          8.4374e-03]], requires_grad=True)
b1 = tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)
W2 = tensor([[ 0.0091, -0.0012, -0.0102,  0.0100,  0.0161, -0.0050,  0.0143,  0.0006],
        [-0.0039,  0.0041, -0.0087,  0.0142,  0.0039, -0.0031,  0.0019,  0.0120],
        [-0.0070,  0.0281,  0.0018,  0.0053,  0.0045, -0.0003, -0.0001, -0.0074],
        [-0.0191, -0.0072,  0.0091,  0.0001,  0.0068, -0.0254, -0.0016,  0.0009],
        [ 0.0200,  0.0017,  0.0075, -0.0196,  0.0103,  0.0200,  0.0174, -0.0241],
        [-0.0096,  0.0159,  0.0097,  0.0070, -0.0055, -0.0023, -0.0115,  0.0076],
        [ 0.0073,  0.0105, -0.0044, -0.0135,  0.0182, -0.0018, -0.0080,  0.0149],
        [-0.0043, -0.0105,  0.0181,  0.0125, -0.0024, -0.0003,  0.0099,  0.0210],
        [ 0.0094, -0.0031,  0.0018, -0.0020, -0.0034, -0.0029,  0.0095, -0.0158],
        [-0.0047,  0.0032,  0.0027, -0.0069,  0.0042,  0.0031, -0.0068, -0.0062],
        [ 0.0198, -0.0005, -0.0070, -0.0032,  0.0099,  0.0090,  0.0213, -0.0052],
        [-0.0061,  0.0007,  0.0069, -0.0084,  0.0116,  0.0068, -0.0054,  0.0131],
        [-0.0056, -0.0051,  0.0055, -0.0010,  0.0079, -0.0091, -0.0085,  0.0194],
        [ 0.0112,  0.0040,  0.0073, -0.0013,  0.0094,  0.0078,  0.0129, -0.0278],
        [ 0.0108, -0.0088, -0.0024,  0.0019,  0.0038,  0.0111, -0.0097, -0.0023],
        [-0.0062,  0.0136, -0.0110,  0.0084,  0.0164,  0.0217, -0.0096,  0.0006]],
       requires_grad=True)
b2 = tensor([0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)
W3 = tensor([[ 0.0027],
        [-0.0012],
        [ 0.0049],
        [-0.0006],
        [ 0.0074],
        [ 0.0014],
        [-0.0062],
        [-0.0104]], requires_grad=True)
b3 = tensor([0.], requires_grad=True)

In [53]:
optimizer = torch.optim.SGD([W1, b1, W2, b2, W3, b3], lr=0.05)

In [54]:
import torch.nn.functional as F

for epoch in range(10000):
    optimizer.zero_grad()

    z1 = X @ W1 + b1  # first linear value
    a1 = torch.clip(z1, 0.)  # ReLU

    z2 = a1 @ W2 + b2  # second linear value
    a2 = torch.clip(z2, 0.) # ReLU

    preds = torch.sigmoid(a2 @ W3 + b3)
    loss = F.l1_loss(preds, y)

    loss.backward()  # gradients
    optimizer.step()  # gradient descent step

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.5000
Epoch 50, Loss: 0.4924
Epoch 100, Loss: 0.4849
Epoch 150, Loss: 0.4776
Epoch 200, Loss: 0.4708
Epoch 250, Loss: 0.4644
Epoch 300, Loss: 0.4585
Epoch 350, Loss: 0.4531
Epoch 400, Loss: 0.4481
Epoch 450, Loss: 0.4437
Epoch 500, Loss: 0.4397
Epoch 550, Loss: 0.4361
Epoch 600, Loss: 0.4329
Epoch 650, Loss: 0.4299
Epoch 700, Loss: 0.4273
Epoch 750, Loss: 0.4250
Epoch 800, Loss: 0.4228
Epoch 850, Loss: 0.4209
Epoch 900, Loss: 0.4191
Epoch 950, Loss: 0.4175
Epoch 1000, Loss: 0.4161
Epoch 1050, Loss: 0.4147
Epoch 1100, Loss: 0.4135
Epoch 1150, Loss: 0.4124
Epoch 1200, Loss: 0.4114
Epoch 1250, Loss: 0.4104
Epoch 1300, Loss: 0.4095
Epoch 1350, Loss: 0.4087
Epoch 1400, Loss: 0.4079
Epoch 1450, Loss: 0.4072
Epoch 1500, Loss: 0.4066
Epoch 1550, Loss: 0.4059
Epoch 1600, Loss: 0.4054
Epoch 1650, Loss: 0.4048
Epoch 1700, Loss: 0.4043
Epoch 1750, Loss: 0.4038
Epoch 1800, Loss: 0.4034
Epoch 1850, Loss: 0.4029
Epoch 1900, Loss: 0.4025
Epoch 1950, Loss: 0.4022
Epoch 2000, Loss: 0.4018
Epoch 2050, Loss: 0.4014
Epoch 2100, Loss: 0.4011
Epoch 2150, Loss: 0.4008
Epoch 2200, Loss: 0.4005
Epoch 2250, Loss: 0.4002
Epoch 2300, Loss: 0.4000
Epoch 2350, Loss: 0.3997
Epoch 2400, Loss: 0.3994
Epoch 2450, Loss: 0.3992
Epoch 2500, Loss: 0.3990
Epoch 2550, Loss: 0.3988
Epoch 2600, Loss: 0.3986
Epoch 2650, Loss: 0.3984
Epoch 2700, Loss: 0.3982
Epoch 2750, Loss: 0.3980
Epoch 2800, Loss: 0.3978
Epoch 2850, Loss: 0.3976
Epoch 2900, Loss: 0.3975
Epoch 2950, Loss: 0.3973
Epoch 3000, Loss: 0.3972
Epoch 3050, Loss: 0.3970
Epoch 3100, Loss: 0.3969
Epoch 3150, Loss: 0.3967
Epoch 3200, Loss: 0.3966
Epoch 3250, Loss: 0.3965
Epoch 3300, Loss: 0.3963
Epoch 3350, Loss: 0.3962
Epoch 3400, Loss: 0.3961
Epoch 3450, Loss: 0.3960
Epoch 3500, Loss: 0.3959
Epoch 3550, Loss: 0.3958
Epoch 3600, Loss: 0.3957
Epoch 3650, Loss: 0.3956
Epoch 3700, Loss: 0.3955
Epoch 3750, Loss: 0.3954
Epoch 3800, Loss: 0.3953
Epoch 3850, Loss: 0.3952
Epoch 3900, Loss: 0.3951
Epoch 3950, Loss: 0.3950
Epoch 4000, Loss: 0.3949
Epoch 4050, Loss: 0.3949
Epoch 4100, Loss: 0.3948
Epoch 4150, Loss: 0.3947
Epoch 4200, Loss: 0.3946
Epoch 4250, Loss: 0.3945
Epoch 4300, Loss: 0.3945
Epoch 4350, Loss: 0.3944
Epoch 4400, Loss: 0.3943
Epoch 4450, Loss: 0.3943
Epoch 4500, Loss: 0.3942
Epoch 4550, Loss: 0.3941
Epoch 4600, Loss: 0.3941
Epoch 4650, Loss: 0.3940
Epoch 4700, Loss: 0.3940
Epoch 4750, Loss: 0.3939
Epoch 4800, Loss: 0.3938
Epoch 4850, Loss: 0.3938
Epoch 4900, Loss: 0.3937
Epoch 4950, Loss: 0.3937
Epoch 5000, Loss: 0.3936
Epoch 5050, Loss: 0.3936
Epoch 5100, Loss: 0.3935
Epoch 5150, Loss: 0.3935
Epoch 5200, Loss: 0.3934
Epoch 5250, Loss: 0.3934
Epoch 5300, Loss: 0.3933
Epoch 5350, Loss: 0.3933
Epoch 5400, Loss: 0.3933
Epoch 5450, Loss: 0.3932
Epoch 5500, Loss: 0.3932
Epoch 5550, Loss: 0.3931
Epoch 5600, Loss: 0.3931
Epoch 5650, Loss: 0.3930
Epoch 5700, Loss: 0.3930
Epoch 5750, Loss: 0.3930
Epoch 5800, Loss: 0.3929
Epoch 5850, Loss: 0.3929
Epoch 5900, Loss: 0.3929
Epoch 5950, Loss: 0.3928
Epoch 6000, Loss: 0.3928
Epoch 6050, Loss: 0.3927
Epoch 6100, Loss: 0.3927
Epoch 6150, Loss: 0.3927
Epoch 6200, Loss: 0.3926
Epoch 6250, Loss: 0.3926
Epoch 6300, Loss: 0.3926
Epoch 6350, Loss: 0.3925
Epoch 6400, Loss: 0.3925
Epoch 6450, Loss: 0.3925
Epoch 6500, Loss: 0.3925
Epoch 6550, Loss: 0.3924
Epoch 6600, Loss: 0.3924
Epoch 6650, Loss: 0.3924
Epoch 6700, Loss: 0.3923
Epoch 6750, Loss: 0.3923
Epoch 6800, Loss: 0.3923
Epoch 6850, Loss: 0.3923
Epoch 6900, Loss: 0.3922
Epoch 6950, Loss: 0.3922
Epoch 7000, Loss: 0.3922
Epoch 7050, Loss: 0.3921
Epoch 7100, Loss: 0.3921
Epoch 7150, Loss: 0.3921
Epoch 7200, Loss: 0.3921
Epoch 7250, Loss: 0.3920
Epoch 7300, Loss: 0.3920
Epoch 7350, Loss: 0.3920
Epoch 7400, Loss: 0.3920
Epoch 7450, Loss: 0.3920
Epoch 7500, Loss: 0.3919
Epoch 7550, Loss: 0.3919
Epoch 7600, Loss: 0.3919
Epoch 7650, Loss: 0.3919
Epoch 7700, Loss: 0.3918
Epoch 7750, Loss: 0.3918
Epoch 7800, Loss: 0.3918
Epoch 7850, Loss: 0.3918
Epoch 7900, Loss: 0.3918
Epoch 7950, Loss: 0.3917
Epoch 8000, Loss: 0.3917
Epoch 8050, Loss: 0.3917
Epoch 8100, Loss: 0.3917
Epoch 8150, Loss: 0.3917
Epoch 8200, Loss: 0.3916
Epoch 8250, Loss: 0.3916
Epoch 8300, Loss: 0.3916
Epoch 8350, Loss: 0.3916
Epoch 8400, Loss: 0.3916
Epoch 8450, Loss: 0.3916
Epoch 8500, Loss: 0.3915
Epoch 8550, Loss: 0.3915
Epoch 8600, Loss: 0.3915
Epoch 8650, Loss: 0.3915
Epoch 8700, Loss: 0.3915
Epoch 8750, Loss: 0.3915
Epoch 8800, Loss: 0.3914
Epoch 8850, Loss: 0.3914
Epoch 8900, Loss: 0.3914
Epoch 8950, Loss: 0.3914
Epoch 9000, Loss: 0.3914
Epoch 9050, Loss: 0.3914
Epoch 9100, Loss: 0.3913
Epoch 9150, Loss: 0.3913
Epoch 9200, Loss: 0.3913
Epoch 9250, Loss: 0.3913
Epoch 9300, Loss: 0.3913
Epoch 9350, Loss: 0.3913
Epoch 9400, Loss: 0.3913
Epoch 9450, Loss: 0.3912
Epoch 9500, Loss: 0.3912
Epoch 9550, Loss: 0.3912
Epoch 9600, Loss: 0.3912
Epoch 9650, Loss: 0.3912
Epoch 9700, Loss: 0.3912
Epoch 9750, Loss: 0.3912
Epoch 9800, Loss: 0.3911
Epoch 9850, Loss: 0.3911
Epoch 9900, Loss: 0.3911
Epoch 9950, Loss: 0.3911