In [210]:
# load the dataset
import pandas as pd
df = pd.read_csv("train.csv")

In [211]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [235]:
df.Parch.max()

np.int64(6)

In [212]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [213]:
# Drop irrelevent columns
df = df.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis=1)

#check the results
df.head(10)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S
5         0       3    male   NaN      0      0   8.4583        Q
6         0       1    male  54.0      0      0  51.8625        S
7         0       3    male   2.0      3      1  21.0750        S
8         1       3  female  27.0      0      2  11.1333        S
9         1       2  female  14.0      1      0  30.0708        C

In [214]:
# one-hot encode the "Pclass" column
df = pd.get_dummies(df, columns=['Pclass'], drop_first=True)

df.head(10)

   Survived     Sex   Age  SibSp  Parch     Fare Embarked  Pclass_2  Pclass_3
0         0    male  22.0      1      0   7.2500        S     False      True
1         1  female  38.0      1      0  71.2833        C     False     False
2         1  female  26.0      0      0   7.9250        S     False      True
3         1  female  35.0      1      0  53.1000        S     False     False
4         0    male  35.0      0      0   8.0500        S     False      True
5         0    male   NaN      0      0   8.4583        Q     False      True
6         0    male  54.0      0      0  51.8625        S     False     False
7         0    male   2.0      3      1  21.0750        S     False      True
8         1  female  27.0      0      2  11.1333        S     False      True
9         1  female  14.0      1      0  30.0708        C      True     False

In [215]:
# One-hot encode the 'Emberked' column
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,male,22.0,1,0,7.2500,False,True,False,True
1,1,female,38.0,1,0,71.2833,False,False,False,False
2,1,female,26.0,0,0,7.9250,False,True,False,True
3,1,female,35.0,1,0,53.1000,False,False,False,True
4,0,male,35.0,0,0,8.0500,False,True,False,True
5,0,male,NaN,0,0,8.4583,False,True,True,False
6,0,male,54.0,0,0,51.8625,False,False,False,True
7,0,male,2.0,3,1,21.0750,False,True,False,True
8,1,female,27.0,0,2,11.1333,False,True,False,True
9,1,female,14.0,1,0,30.0708,True,False,False,False

In [216]:
df["Sex"] = df["Sex"].map({"male": 0, "female": 1})

In [217]:
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False
2,1,1,26.0,0,0,7.9250,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,True
4,0,0,35.0,0,0,8.0500,False,True,False,True
5,0,0,NaN,0,0,8.4583,False,True,True,False
6,0,0,54.0,0,0,51.8625,False,False,False,True
7,0,0,2.0,3,1,21.0750,False,True,False,True
8,1,1,27.0,0,2,11.1333,False,True,False,True
9,1,1,14.0,1,0,30.0708,True,False,False,False

In [218]:
df.isna().sum()

Survived        0
Sex             0
Age           177
SibSp           0
Parch           0
Fare            0
Pclass_2        0
Pclass_3        0
Embarked_Q      0
Embarked_S      0
dtype: int64

Applying inputation

In [219]:
# Calculate median age
median_age = df['Age'].median()
print(median_age)

28.0

In [220]:
df.fillna({'Age':median_age},inplace=True)
df.isna().sum()

Survived      0
Sex           0
Age           0
SibSp         0
Parch         0
Fare          0
Pclass_2      0
Pclass_3      0
Embarked_Q    0
Embarked_S    0
dtype: int64

In [221]:
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,False,True,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False
2,1,1,26.0,0,0,7.9250,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,True
4,0,0,35.0,0,0,8.0500,False,True,False,True
5,0,0,28.0,0,0,8.4583,False,True,True,False
6,0,0,54.0,0,0,51.8625,False,False,False,True
7,0,0,2.0,3,1,21.0750,False,True,False,True
8,1,1,27.0,0,2,11.1333,False,True,False,True
9,1,1,14.0,1,0,30.0708,True,False,False,False

In [222]:
# Convert boolean columns to integers (True -> 1, False -> 0)
boolean_cols = ['Pclass_2', 'Pclass_3', 'Embarked_Q', 'Embarked_S']
for col in boolean_cols:
    df[col] = df[col].astype(int)

# Re-check the head to confirm the conversion
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S
0,0,0,22.0,1,0,7.2500,0,1,0,1
1,1,1,38.0,1,0,71.2833,0,0,0,0
2,1,1,26.0,0,0,7.9250,0,1,0,1
3,1,1,35.0,1,0,53.1000,0,0,0,1
4,0,0,35.0,0,0,8.0500,0,1,0,1
5,0,0,28.0,0,0,8.4583,0,1,1,0
6,0,0,54.0,0,0,51.8625,0,0,0,1
7,0,0,2.0,3,1,21.0750,0,1,0,1
8,1,1,27.0,0,2,11.1333,0,1,0,1
9,1,1,14.0,1,0,30.0708,1,0,0,0

Normalize the Age Value

In [223]:
# Find the maximum age in the dataset
max_age = df["Age"].max()
print(max_age)

df["Age_Normalized"] = df["Age"] / max_age
df.head()

80.0

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized
0,0,0,22.0,1,0,7.2500,0,1,0,1,0.2750
1,1,1,38.0,1,0,71.2833,0,0,0,0,0.4750
2,1,1,26.0,0,0,7.9250,0,1,0,1,0.3250
3,1,1,35.0,1,0,53.1000,0,0,0,1,0.4375
4,0,0,35.0,0,0,8.0500,0,1,0,1,0.4375

In [224]:
# Check for zeros in the 'Fare' column
zero_count = (df['Fare'] == 0).sum()

if zero_count > 0:
    print(f"✅ Yes, the 'Fare' column contains {zero_count} zero(s).")
else:
    print("✅ No zeros found in the 'Fare' column.")

✅ Yes, the 'Fare' column contains 15 zero(s).

In [225]:
#remove Fare 0
df_cleaned = df[df['Fare'] != 0].copy()
df = df_cleaned

Scale the fare

In [226]:
import numpy as np
df['Log_Fare'] = np.log10(df['Fare'])
df.head(10)

,Survived,Sex,Age,SibSp,Parch,Fare,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized,Log_Fare
0,0,0,22.0,1,0,7.2500,0,1,0,1,0.2750,0.860338
1,1,1,38.0,1,0,71.2833,0,0,0,0,0.4750,1.852988
2,1,1,26.0,0,0,7.9250,0,1,0,1,0.3250,0.898999
3,1,1,35.0,1,0,53.1000,0,0,0,1,0.4375,1.725095
4,0,0,35.0,0,0,8.0500,0,1,0,1,0.4375,0.905796
5,0,0,28.0,0,0,8.4583,0,1,1,0,0.3500,0.927283
6,0,0,54.0,0,0,51.8625,0,0,0,1,0.6750,1.714853
7,0,0,2.0,3,1,21.0750,0,1,0,1,0.0250,1.323768
8,1,1,27.0,0,2,11.1333,0,1,0,1,0.3375,1.046624
9,1,1,14.0,1,0,30.0708,1,0,0,0,0.1750,1.478145

In [227]:
# Separate feature(X) and target (y)
X = df.drop(['Survived','Age','Fare'], axis=1,)
y = df['Survived']

In [228]:
X.head()

,Sex,SibSp,Parch,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Age_Normalized,Log_Fare
0,0,1,0,0,1,0,1,0.2750,0.860338
1,1,1,0,0,0,0,0,0.4750,1.852988
2,1,0,0,0,1,0,1,0.3250,0.898999
3,1,1,0,0,0,0,1,0.4375,1.725095
4,0,0,0,0,1,0,1,0.4375,0.905796

In [230]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [231]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [233]:
print(X)

     Sex  SibSp  Parch  Pclass_2  Pclass_3  Embarked_Q  Embarked_S  \
0      0      1      0         0         1           0           1
1      1      1      0         0         0           0           0
2      1      0      0         0         1           0           1
3      1      1      0         0         0           0           1
4      0      0      0         0         1           0           1
..   ...    ...    ...       ...       ...         ...         ...
886    0      0      0         1         0           0           1
887    1      0      0         0         0           0           1
888    1      1      2         0         1           0           1
889    0      0      0         0         0           0           0
890    0      0      0         0         1           1           0

     Age_Normalized  Log_Fare
0            0.2750  0.860338
1            0.4750  1.852988
2            0.3250  0.898999
3            0.4375  1.725095
4            0.4375  0.905796
..              ...       ...
886          0.3375  1.113943
887          0.2375  1.477121
888          0.3500  1.370143
889          0.3250  1.477121
890          0.4000  0.889302

[876 rows x 9 columns]

In [234]:
# Convert to PyTorch Tensors
X_tensor = torch.tensor(X.to_numpy(dtype="float32"))
y_tensor = torch.tensor(y.to_numpy(dtype="float32")).view(-1, 1)

In [ ]:
X = X_tensor
y = y_tensor

N, D = X.shape
H1, H2 = 16, 8   # two sets of neurons (hidden layers)

# 1) Parameters
W1 = (torch.randn(D, H1) * 0.01).requires_grad_()
b1 = torch.zeros(H1, requires_grad=True)

W2 = (torch.randn(H1, H2) * 0.01).requires_grad_()
b2 = torch.zeros(H2, requires_grad=True)

W3 = (torch.randn(H2, 1) * 0.01).requires_grad_()
b3 = torch.zeros(1, requires_grad=True)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       requires_grad=True)

In [239]:
optimizer = torch.optim.SGD([W1, b1, W2, b2, W3, b3], lr=0.05)

In [ ]:
import torch.nn.functional as F

for epoch in range(10000):
    optimizer.zero_grad()

    z1 = X @ W1 + b1          # first linear value
    a1 = F.relu(z1)           # ReLU

    z2 = a1 @ W2 + b2         # second linear value
    a2 = F.relu(z2)           # ReLU

    preds = torch.sigmoid(a2 @ W3 + b3)
    loss = F.l1_loss(preds, y)

    loss.backward()           # gradients
    optimizer.step()          # gradient descent step

    if epoch % 50 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 0.6684
Epoch 50, Loss: 0.6684
Epoch 100, Loss: 0.6684
Epoch 150, Loss: 0.6684
Epoch 200, Loss: 0.6684
Epoch 250, Loss: 0.6684
Epoch 300, Loss: 0.6684
Epoch 350, Loss: 0.6684
Epoch 400, Loss: 0.6684
Epoch 450, Loss: 0.6684
Epoch 500, Loss: 0.6684
Epoch 550, Loss: 0.6684
Epoch 600, Loss: 0.6684
Epoch 650, Loss: 0.6684
Epoch 700, Loss: 0.6684
Epoch 750, Loss: 0.6684
Epoch 800, Loss: 0.6684
Epoch 850, Loss: 0.6684
Epoch 900, Loss: 0.6684
Epoch 950, Loss: 0.6684
Epoch 1000, Loss: 0.6684
Epoch 1050, Loss: 0.6684
Epoch 1100, Loss: 0.6684
Epoch 1150, Loss: 0.6684
Epoch 1200, Loss: 0.6684
Epoch 1250, Loss: 0.6684
Epoch 1300, Loss: 0.6684
Epoch 1350, Loss: 0.6684
Epoch 1400, Loss: 0.6684
Epoch 1450, Loss: 0.6684
Epoch 1500, Loss: 0.6684
Epoch 1550, Loss: 0.6684
Epoch 1600, Loss: 0.6684
Epoch 1650, Loss: 0.6684
Epoch 1700, Loss: 0.6684
Epoch 1750, Loss: 0.6684
Epoch 1800, Loss: 0.6684
Epoch 1850, Loss: 0.6684
Epoch 1900, Loss: 0.6684
Epoch 1950, Loss: 0.6684
Epoch 2000, Loss: 0.6684
Epoch 2050, Loss: 0.6684
Epoch 2100, Loss: 0.6684
Epoch 2150, Loss: 0.6684
Epoch 2200, Loss: 0.6684
Epoch 2250, Loss: 0.6684
Epoch 2300, Loss: 0.6684
Epoch 2350, Loss: 0.6684
Epoch 2400, Loss: 0.6684
Epoch 2450, Loss: 0.6684
Epoch 2500, Loss: 0.6683
Epoch 2550, Loss: 0.6683
Epoch 2600, Loss: 0.6683
Epoch 2650, Loss: 0.6683
Epoch 2700, Loss: 0.6683
Epoch 2750, Loss: 0.6683
Epoch 2800, Loss: 0.6683
Epoch 2850, Loss: 0.6683
Epoch 2900, Loss: 0.6683
Epoch 2950, Loss: 0.6682
Epoch 3000, Loss: 0.6682
Epoch 3050, Loss: 0.6682
Epoch 3100, Loss: 0.6682
Epoch 3150, Loss: 0.6681
Epoch 3200, Loss: 0.6681
Epoch 3250, Loss: 0.6680
Epoch 3300, Loss: 0.6679
Epoch 3350, Loss: 0.6679
Epoch 3400, Loss: 0.6678
Epoch 3450, Loss: 0.6676
Epoch 3500, Loss: 0.6675
Epoch 3550, Loss: 0.6673
Epoch 3600, Loss: 0.6670
Epoch 3650, Loss: 0.6666
Epoch 3700, Loss: 0.6661
Epoch 3750, Loss: 0.6653
Epoch 3800, Loss: 0.6642
Epoch 3850, Loss: 0.6626
Epoch 3900, Loss: 0.6601
Epoch 3950, Loss: 0.6560
Epoch 4000, Loss: 0.6491
Epoch 4050, Loss: 0.6371
Epoch 4100, Loss: 0.6158
Epoch 4150, Loss: 0.5802
Epoch 4200, Loss: 0.5327
Epoch 4250, Loss: 0.4902
Epoch 4300, Loss: 0.4660
Epoch 4350, Loss: 0.4557
Epoch 4400, Loss: 0.4514
Epoch 4450, Loss: 0.4493
Epoch 4500, Loss: 0.4480
Epoch 4550, Loss: 0.4468
Epoch 4600, Loss: 0.4454
Epoch 4650, Loss: 0.4441
Epoch 4700, Loss: 0.4419
Epoch 4750, Loss: 0.4398
Epoch 4800, Loss: 0.4382
Epoch 4850, Loss: 0.4370
Epoch 4900, Loss: 0.4359
Epoch 4950, Loss: 0.4351
Epoch 5000, Loss: 0.4344
Epoch 5050, Loss: 0.4338
Epoch 5100, Loss: 0.4332
Epoch 5150, Loss: 0.4327
Epoch 5200, Loss: 0.4323
Epoch 5250, Loss: 0.4320
Epoch 5300, Loss: 0.4316
Epoch 5350, Loss: 0.4313
Epoch 5400, Loss: 0.4310
Epoch 5450, Loss: 0.4308
Epoch 5500, Loss: 0.4305
Epoch 5550, Loss: 0.4303
Epoch 5600, Loss: 0.4300
Epoch 5650, Loss: 0.4298
Epoch 5700, Loss: 0.4296
Epoch 5750, Loss: 0.4294
Epoch 5800, Loss: 0.4293
Epoch 5850, Loss: 0.4291
Epoch 5900, Loss: 0.4289
Epoch 5950, Loss: 0.4288
Epoch 6000, Loss: 0.4286
Epoch 6050, Loss: 0.4284
Epoch 6100, Loss: 0.4282
Epoch 6150, Loss: 0.4280
Epoch 6200, Loss: 0.4279
Epoch 6250, Loss: 0.4277
Epoch 6300, Loss: 0.4275
Epoch 6350, Loss: 0.4273
Epoch 6400, Loss: 0.4272
Epoch 6450, Loss: 0.4270
Epoch 6500, Loss: 0.4268
Epoch 6550, Loss: 0.4267
Epoch 6600, Loss: 0.4265
Epoch 6650, Loss: 0.4263
Epoch 6700, Loss: 0.4261
Epoch 6750, Loss: 0.4259
Epoch 6800, Loss: 0.4257
Epoch 6850, Loss: 0.4255
Epoch 6900, Loss: 0.4253
Epoch 6950, Loss: 0.4251
Epoch 7000, Loss: 0.4249
Epoch 7050, Loss: 0.4246
Epoch 7100, Loss: 0.4244
Epoch 7150, Loss: 0.4242
Epoch 7200, Loss: 0.4240
Epoch 7250, Loss: 0.4237
Epoch 7300, Loss: 0.4235
Epoch 7350, Loss: 0.4233
Epoch 7400, Loss: 0.4231
Epoch 7450, Loss: 0.4228
Epoch 7500, Loss: 0.4226
Epoch 7550, Loss: 0.4224
Epoch 7600, Loss: 0.4221
Epoch 7650, Loss: 0.4219
Epoch 7700, Loss: 0.4216
Epoch 7750, Loss: 0.4214
Epoch 7800, Loss: 0.4211
Epoch 7850, Loss: 0.4208
Epoch 7900, Loss: 0.4205
Epoch 7950, Loss: 0.4202
Epoch 8000, Loss: 0.4198
Epoch 8050, Loss: 0.4193
Epoch 8100, Loss: 0.4190
Epoch 8150, Loss: 0.4186
Epoch 8200, Loss: 0.4183
Epoch 8250, Loss: 0.4179
Epoch 8300, Loss: 0.4176
Epoch 8350, Loss: 0.4173
Epoch 8400, Loss: 0.4169
Epoch 8450, Loss: 0.4166
Epoch 8500, Loss: 0.4163
Epoch 8550, Loss: 0.4159
Epoch 8600, Loss: 0.4156
Epoch 8650, Loss: 0.4153
Epoch 8700, Loss: 0.4150
Epoch 8750, Loss: 0.4147
Epoch 8800, Loss: 0.4143
Epoch 8850, Loss: 0.4140
Epoch 8900, Loss: 0.4137
Epoch 8950, Loss: 0.4133
Epoch 9000, Loss: 0.4129
Epoch 9050, Loss: 0.4125
Epoch 9100, Loss: 0.4122
Epoch 9150, Loss: 0.4118
Epoch 9200, Loss: 0.4115
Epoch 9250, Loss: 0.4112
Epoch 9300, Loss: 0.4109
Epoch 9350, Loss: 0.4106
Epoch 9400, Loss: 0.4103
Epoch 9450, Loss: 0.4100
Epoch 9500, Loss: 0.4097
Epoch 9550, Loss: 0.4094
Epoch 9600, Loss: 0.4090
Epoch 9650, Loss: 0.4087
Epoch 9700, Loss: 0.4083
Epoch 9750, Loss: 0.4079
Epoch 9800, Loss: 0.4076
Epoch 9850, Loss: 0.4073
Epoch 9900, Loss: 0.4069
Epoch 9950, Loss: 0.4065